= Projet Android

Damien Le Garrec,  Nicolas Pietraru


== Presentation


L'application de rendez-vous géolocalisé offre plusieurs possibilités :

* *L'affichage des Rendez vous* qui permet de visualiser la liste de tous
les rendez-vous programmés avec la date et leurs états de réceptions(en cours, accepté).
* *La visualisation sur googleMap du rendez vous* permettant
d'ouvrir une googleMap aux coordonnées du rendez-vous
* *La reception d'un rendez-vous* envoyé par un autre utilisateur
* *L'acceptation d'un rendez-vous* pour enregistrer le rendez vous et le notifier à l'envoyeur
* *Le refus d'un rendez-vous* pour notifier l'envoyeur
* *L'envoi d'un rendez-vous* avec la position actuelle ou renseigné ainsi qu'une date.

== Architecture technique 

L'architecture est decomposé en 3 packages specialisés :

* *Les activities* qui assure la gestion de l'interface
* *Les entities* qui sont tous les objets utilisés dans l'application
* *Les DAO* qui assure l'abstraction entre la base de données et le métier

== Architecture fonctionnel

* *Page Principal* message de bienvenue, bouton d'envoi de demande de rendez-vous, affichage de la liste des rendez-vous avec leur statut
* *Page Demande de Rendez-vous* Renseignement du numero du destinataire, ajout des coordonnées (facultatif), date du rendez-vous, bouton envoyer
* *Page retour de notification* au clique sur la notification une nouvelle page s'ouvre avec le récap du rendez-vous et la possibilité d'accepter ou d'annuler.


== Evolution envisageable

Différentes évolutions peuvent être envisagées pour l'application:
* la mise en place d'un serveur distant permettant d'avoir une
base de données des utilisateurs afin de faire évoluer la communication entre utilisateur et non entre numéros de telephone;
* La création d'un serveur de notifications pour ne plus devoir passer par l'envoi de sms.